### ISSUE TITLE
Assignment 1, Question 4: template error?

### ISSUE THREAD

**Issue by finnss** [wakita/fp2018#1]
Hey!

The question text of Question 4 of the first assignment states `Define ack that computes Ackermann function as defined in Wikipedia`. 

However, the template for the answer to question is
``` oCaml
(* Q4 *)
type number = Int of int | Float of float | Error;;
type sign = Positive | Negative;;

let sign_int n =
  if n >= 0 then Positive
  else Negative;;

let div_num n1 n2 =
  Error;;
```

This doesn't seem relevant to the problem? Am I misunderstanding perhaps, or could this be an unintentional remnant of the previous version of the assignment?

Also, as a minor detail, there is no `(* Q5 *)` "title" above the template for question 5. 

Sorry in advance if it's my mistake!

**Comment by wakita** [comment]
Thanks!  I will fix it.

**Comment by wakita** [comment]
Here is the fix
https://github.com/wakita/fp2018/commit/dee3b15528403a776ca0400a7a23cc72df48fe2b
