### ISSUE TITLE
Day 3, Quiz 3: `is_binary_search_tree` does not check descendant nodes sufficiently

### ISSUE THREAD

**Issue by lo48576** [wakita/fp2018#2]
Every binary search tree node should have greater or equal value than any descendants of the left child tree, and smaller value than any descendants of the right child tree.
But the answer for Q3 in the slide checks only child nodes, not all descendants.

https://github.com/wakita/fp2018/blob/af044cb049f21754382b71884978861662152665/docs/ocaml/03-exercise.ml#L34-L42

So, here is a counter example: The tree `ce` below has value `5` and passes the test `is_binary_search_tree`, but it cannot be found by `member` function (binary search).

`20181004.ml`:
```ocaml
type 'a binary_tree =
  Empty
| Node of 'a * 'a binary_tree * 'a binary_tree;;

let rec member x tree =
  match tree with
    Empty -> false
  | Node(y, left, right) ->
      if x = y then true else
      if x < y then member x left else member x right;;

(* counter-example *)
let ce = Node(4, Node(2, Node(1, Empty, Empty), Node(5, Empty, Empty)), Node(6, Empty, Empty));;

let is_binary_search_tree t =
  let rec aux test t =
    match t with
      | Empty -> true
      | Node(y, left, right) ->
          test y &&
          aux (function x -> x < y) left &&
          aux (function x -> x > y) right in
  aux (function _ -> true) t;;
```

REPL:
```
$ ocaml
        OCaml version 4.05.0

# #use "20181004.ml";;
type 'a binary_tree = Empty | Node of 'a * 'a binary_tree * 'a binary_tree
val member : 'a -> 'a binary_tree -> bool = <fun>
val ce : int binary_tree =
  Node (4, Node (2, Node (1, Empty, Empty), Node (5, Empty, Empty)),
   Node (6, Empty, Empty))
val is_binary_search_tree : 'a binary_tree -> bool = <fun>
# is_binary_search_tree ce;;
- : bool = true
# member 5 ce;;
- : bool = false
#
```

**Comment by wakita** [comment]
@lo48576 Thanks for your report and sending in a counter example.  Yes, you are right!  I will publish a fix soon.  An easy fix is to have the proposition passed via the function argument to be tested with in the two function closures (I will present this solution) but its not efficient.  A better approach is to pass a range of permissible values (instead of the closure) and perform an in-range testing for the LHS and RHS subtrees.

**Comment by wakita** [comment]
Here follows the easy fix (inefficient version):

```
let is_binary_search_tree t =
  let rec aux test t =
    match t with
      | Empty -> true
      | Node(y, left, right) ->
          test y &&
          aux (function x -> test x && x < y) left &&
          aux (function x -> test x && x > y) right in
  aux (function _ -> true) t;;
```

**Comment by wakita** [comment]
and here follows the efficient version:

```let rec is_binary_search_tree t =
  let rec aux (l, r) t =
    match t with
    | Empty -> true
    | Node(v, left, right) ->
        l < v && v < r && aux (l, v) left && aux(v, r) right in
  aux (min_int, max_int) t;;
```

**Comment by wakita** [comment]
Including the one using the `values` function, we have three different solutions in total.

**Comment by wakita** [comment]
Please refer to 
https://wakita.github.io/fp2018/ocaml/to-appear-after-the-class.ml

00c50988a509e9a36de33368f1d3029f9114cc4e
