### ISSUE TITLE
When will the second coding assignment be posted?

### ISSUE THREAD

**Issue by mikecat** [wakita/fp2018#3]
It was said that "The second coding assignment will be posted tonight at OCW-i." in the [lecture on Oct. 4](https://wakita.github.io/fp2018/slide/03-ocaml2.html#/assignment-to-be-announced).
A week has passed since then, but there doesn't seem the assignment posted yet.
I have submitted an answer for the first assignment via OCW-i, so I don't think I haven't registered properly.
When will actually the second coding assignment will be posted?

**Comment by wakita** [comment]
Thanks for reporting on this!

I forgot about this.  I will add an assignment this weekend.

Sorry again for not responding to your message earlier.  I have added a Slack integration of this repository.
